### ISSUE TITLE
resolve.sync doesn't respect NODE_PATH

### ISSUE THREAD

**Issue by shlevy** [substack/node-resolve#39] opened 2013-12-31 21:38 UTC
There is an inconsistency in how `resolve.sync` and `require.resolve` resolve paths:

```
$ NODE_PATH=/opt/grunt-0.4.2/lib/node_modules node
> require.resolve('grunt')
'/opt/grunt-0.4.2/lib/node_modules/grunt/lib/grunt.js'
> require('resolve').sync('grunt')
Error: Cannot find module 'grunt' from '.'
    at Function.module.exports [as sync] (/home/shlevy/test/node_modules/resolve/lib/sync.js:32:11)
    at repl:1:21
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:98:17)
>
```

**Comment by callumacrae** [comment] 2015-05-01 15:13
This is still an issue. I'll send a failing test case.

**Comment by carenas** [comment] 2015-08-20 08:37
still see the same inconsistency when using node-resolve 0.3.1, this affects sequelize-cli as can be seen in https://github.com/sequelize/cli/issues/104

**Comment by dsilva** [comment] 2016-03-15 08:18
This issue breaks eslint_d per https://github.com/mantoni/eslint_d.js/issues/36

**Comment by dsilva** [comment] 2016-03-15 16:12
Restoring consistency here between resolve.sync and require.resolve should be a matter of defaulting the "paths" option to require('module').globalPaths, right?

**Comment by guncha** [comment] 2017-06-05 15:20
I don't think that without this the package can make claims like:

> implements the node require.resolve() algorithm

@substack, a lot of people, including me, would be happy to fix this, as long as you or someone else will review and merge the PRs.

**Comment by ljharb** [comment] 2017-06-05 15:47
https://github.com/substack/node-resolve/pull/47#issuecomment-45657329 seems clear.

@guncha you'll note that line in the readme links to the official node resolve algorithm, which *by design* omits all mention of NODE_PATH. If you file an issue on node's website, and they update that page, it'll be a much stronger case to add the behavior here.

Using NODE_PATH is a really bad idea; and when node ships ES module support, it won't have any concept that enables requiring modules in a nonstandard place, so it's best to wean yourself off it asap.

The proper solution right now is to pass `process.env.NODE_PATH` into `opts.path` if you absolutely need to rely on it for some reason.

Per the above comment and the OP, I'll close this for now.

**Closed by ljharb** 2017-06-05 15:47 UTC

**Comment by guncha** [comment] 2017-06-05 17:03
Alright, makes sense. I guess I read the "implements the node `require.resolve()` algorithm" a little too literally.
